import { Box, Grid } from "@mui/material";
import Head from "next/head";
import { Fragment, ReactNode, useState } from "react";
import * as rdd from 'react-device-detect'

import Footer from "../Footer/Footer";
import Header from "../Header/Header";
import Main from "../Main/Main";

// export interface LayoutProps extends React.ComponentPropsWithoutRef<Layout> {
export interface LayoutProps {
  // children: JSX.Element;
  // children: (props: typeof rdd) => ReactNode;
  children: ReactNode;
  // children?: any;
}

export interface LayoutState {
  top?: boolean;
  left?: boolean;
  bottom?: boolean;
  right?: boolean;
  width?: number;
  height?: number;
}

// export default function Layout<LayoutProps, LayoutState>({ children }: LayoutProps) {
// export default function Layout<LayoutProps, LayoutState>: React.FC({ children }: LayoutProps) {
// export default function Layout<LayoutProps, LayoutState>(props: LayoutProps) {
// export default function Layout(props: LayoutProps) {
export default function Layout({ children }: LayoutProps) {

  const [state, setState] = useState({
    top: false,
    left: false,
    bottom: false,
    right: false,
    // width: window.innerWidth,
    // height: window.innerHeight
  });

  const setPartialState = (obj: Partial<typeof state>) =>
    setState({ ...state, ...obj });

  // const isMobile = window.innerWidth <= 500;
  // const isTablet = window.innerWidth <= 800;

  // window.addEventListener('resize', () => setPartialState({
  //   width: window.innerWidth,
  //   height: window.innerHeight
  // }));

  // if (isMobile) {}

  // if (isTablet) {}

  return (
    <Fragment>
      <Head>
        <title>YPO IDE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </Head>

      <Box sx={{
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        flexWrap: "nowrap",
        alignItems: ""
      }}>

        <Header />

        <Main>
          {/* {console.log(rdd)} */}
          {/* {console.log(rdd.isMobile)} */}
          {children}
          {/* {children(rdd)} */}
          {/* {props.children(rdd)} */}
        </Main>

        <Footer />
      </Box>
    </Fragment>
  )
}
