import { Box, Grid, ThemeProvider } from "@mui/material";
import { NextComponentType, NextPage, NextPageContext } from "next";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import { createContext, Fragment, FunctionComponent, ReactNode, useContext, useState } from "react";
import * as rdd from 'react-device-detect'
import lightTheme from "../../styles/theme/lightTheme";
import AppContext from "../../utils/AppContext";

import Footer from "../Footer/Footer";
import Header from "../Header/Header";
import Main from "../Main/Main";

// export interface LayoutProps extends React.ComponentPropsWithoutRef<Layout> {
export interface LayoutProps {
  children: ReactNode;
}

export interface LayoutState {
  top?: boolean;
  left?: boolean;
  bottom?: boolean;
  right?: boolean;
  width?: number;
  height?: number;
}

// Use ThemeContext of MUI
// const ThemeContext = createContext('light');

// export default function Layout<LayoutProps, LayoutState>({ children }: LayoutProps) {
// export default function Layout<LayoutProps, LayoutState>: React.FC({ children }: LayoutProps) {
// export default function Layout<LayoutProps, LayoutState>(props: LayoutProps) {
// export default function Layout(props: LayoutProps) {
// export default function Layout({ children }: LayoutProps) {
export const Layout: NextPage<LayoutProps> = ({ children }: LayoutProps) => {

  // const { session, loading } = useSession();
  // const [session, loading] = useSession();
  const { data, status } = useSession();

  const context = useContext(AppContext);

  const [state, setState] = useState({
    top: false,
    left: false,
    bottom: false,
    right: false,
    // width: window.innerWidth,
    // height: window.innerHeight
  });

  const setPartialState = (obj: Partial<typeof state>) =>
    setState({ ...state, ...obj });

  // const isMobile = window.innerWidth <= 500;
  // const isTablet = window.innerWidth <= 800;

  // window.addEventListener('resize', () => setPartialState({
  //   width: window.innerWidth,
  //   height: window.innerHeight
  // }));

  // if (isMobile) {}

  // if (isTablet) {}

  const getInitialProps = async (context: NextPageContext) => {
    return {
      session: await getSession(context)
    };
  }

  return (
    // <ThemeContext.Provider theme={theme}></ThemeContext.Provider>
    <ThemeProvider theme={lightTheme}>
      <Fragment>
        <Head>
          <title>YPO IDE</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.svg" type="image/svg+xml" />
        </Head>

        <Box sx={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          flexWrap: "nowrap",
          alignItems: ""
        }}>

          <Header />

          <Main>
            {/* {console.log(rdd)} */}
            {/* {console.log(rdd.isMobile)} */}
            {/* {children} */}
            {/* {children(rdd)} */}
            {/* {props.children(rdd)} */}
            <p>
              {!data && <>
                Not signed in <br />
                <a href="/api/auth/signin">Sign in</a>
              </>}
              {data && <>
                Signed in as {data.user.email} <br />
                <a href="/api/auth/signout">Sign out</a>
              </>}
            </p>
          </Main>

          <Footer />
        </Box>
      </Fragment>
    </ThemeProvider>
  )
}

export default Layout;